name: Sync fork
on:
  repository_dispatch: 
  workflow_dispatch:
  schedule:
    - cron: '45 4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    - name: Set env
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config checkout.defaultRemote "origin"
    - name: Update branch master
      run: |
        git remote add upstream https://github.com/yt-dlp/yt-dlp.git
        git remote -v
        git fetch upstream master
        git checkout master
        git rebase --strategy-option=ours upstream/master
        git push -f
    - name: Update branch dev
      run: |
        git checkout -B dev origin/dev -t
        git rebase --strategy-option=ours upstream/master
        git push -f
